version: '3'

services:
  rasa:
    image: audiocodes/rasa:3.1.0
    command: run --debug --port 5006
    restart: always
    depends_on:
      - actions_server
    ports:
      - 5006:5006
    tmpfs: /tmp
    volumes:
      - ./bot:/app

  rasa_ws:
    image: audiocodes/rasa:3.1.0
    build:
      context: docker
    command: run --debug --port 5009
    restart: always
    depends_on:
      - actions_server
    ports:
      - 5009:5009
    tmpfs: /tmp
    volumes:
      - ./bot:/app
      - ./bot/credentials-ws.yml:/app/credentials.yml

  actions_server:
    image: audiocodes/rasa:3.1.0
    command: run actions --port 5059
    restart: always
    tmpfs: /tmp
    volumes:
      - ./bot:/app
